# Generated by Django 4.2.6 on 2023-12-21 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_category_newsarticle_comment_profile_fav_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='fav_categories',
            field=models.ManyToManyField(blank=True, default='Sports', to='api.category'),
        ),
    ]
